# Generated by Django 2.2.4 on 2020-12-17 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_message_bouncer', '0002_auto_20201217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_children', to='drf_message_bouncer.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drf_message_bouncer.Session'),
        ),
    ]
