# Generated by Django 2.2.4 on 2020-12-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_message_bouncer', '0003_auto_20201217_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_children', to='drf_message_bouncer.Message'),
        ),
    ]
