# Generated by Django 2.2.4 on 2020-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_message_bouncer', '0004_auto_20201217_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='message',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='session',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='session',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('session', 'original'), name='unique_session_original'),
        ),
    ]
